//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alchemy.Plugins.Peek {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Alchemy.Plugins.Peek.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No (explicit).
        /// </summary>
        internal static string CannotBePublished {
            get {
                return ResourceManager.GetString("CannotBePublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No (inherited).
        /// </summary>
        internal static string CannotBePublishedDueToAncestor {
            get {
                return ResourceManager.GetString("CannotBePublishedDueToAncestor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1} templates).
        /// </summary>
        internal static string ComponentPresentationSummary {
            get {
                return ResourceManager.GetString("ComponentPresentationSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (one template).
        /// </summary>
        internal static string ComponentPresentationSummarySameTemplate {
            get {
                return ResourceManager.GetString("ComponentPresentationSummarySameTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        internal static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes (allowed on Pages).
        /// </summary>
        internal static string DynamicTemplateAllowedOnPage {
            get {
                return ResourceManager.GetString("DynamicTemplateAllowedOnPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes (not allowed on Pages).
        /// </summary>
        internal static string DynamicTemplateNotAllowedOnPage {
            get {
                return ResourceManager.GetString("DynamicTemplateNotAllowedOnPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (empty).
        /// </summary>
        internal static string EmptyLabel {
            get {
                return ResourceManager.GetString("EmptyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} bytes.
        /// </summary>
        internal static string FileSizeInBytes {
            get {
                return ResourceManager.GetString("FileSizeInBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} GB.
        /// </summary>
        internal static string FileSizeInGigaBytes {
            get {
                return ResourceManager.GetString("FileSizeInGigaBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} KB.
        /// </summary>
        internal static string FileSizeInKiloBytes {
            get {
                return ResourceManager.GetString("FileSizeInKiloBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} MB.
        /// </summary>
        internal static string FileSizeInMegaBytes {
            get {
                return ResourceManager.GetString("FileSizeInMegaBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (in select Publications).
        /// </summary>
        internal static string GroupMembershipSummaryScoped {
            get {
                return ResourceManager.GetString("GroupMembershipSummaryScoped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Publications.
        /// </summary>
        internal static string GroupScopeAllPublications {
            get {
                return ResourceManager.GetString("GroupScopeAllPublications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specific Publications.
        /// </summary>
        internal static string GroupScopeSpecificPublications {
            get {
                return ResourceManager.GetString("GroupScopeSpecificPublications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component Presentations.
        /// </summary>
        internal static string LabelComponentPresentations {
            get {
                return ResourceManager.GetString("LabelComponentPresentations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditions.
        /// </summary>
        internal static string LabelConditions {
            get {
                return ResourceManager.GetString("LabelConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        internal static string LabelCreationDate {
            get {
                return ResourceManager.GetString("LabelCreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Code Page.
        /// </summary>
        internal static string LabelDefaultCodePage {
            get {
                return ResourceManager.GetString("LabelDefaultCodePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string LabelDescription {
            get {
                return ResourceManager.GetString("LabelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destinations.
        /// </summary>
        internal static string LabelDestinations {
            get {
                return ResourceManager.GetString("LabelDestinations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory.
        /// </summary>
        internal static string LabelDirectory {
            get {
                return ResourceManager.GetString("LabelDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamic.
        /// </summary>
        internal static string LabelDynamicTemplateInfo {
            get {
                return ResourceManager.GetString("LabelDynamicTemplateInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension.
        /// </summary>
        internal static string LabelExtension {
            get {
                return ResourceManager.GetString("LabelExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields.
        /// </summary>
        internal static string LabelFieldsSummary {
            get {
                return ResourceManager.GetString("LabelFieldsSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Extensions.
        /// </summary>
        internal static string LabelFileExtensions {
            get {
                return ResourceManager.GetString("LabelFileExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        internal static string LabelFileName {
            get {
                return ResourceManager.GetString("LabelFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Size.
        /// </summary>
        internal static string LabelFileSize {
            get {
                return ResourceManager.GetString("LabelFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Memberships.
        /// </summary>
        internal static string LabelGroupMemberships {
            get {
                return ResourceManager.GetString("LabelGroupMemberships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string LabelID {
            get {
                return ResourceManager.GetString("LabelID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abstract.
        /// </summary>
        internal static string LabelIsAbstract {
            get {
                return ResourceManager.GetString("LabelIsAbstract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        internal static string LabelIsAdministrator {
            get {
                return ResourceManager.GetString("LabelIsAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        internal static string LabelKey {
            get {
                return ResourceManager.GetString("LabelKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string LabelLanguage {
            get {
                return ResourceManager.GetString("LabelLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linked Schema.
        /// </summary>
        internal static string LabelLinkedSchema {
            get {
                return ResourceManager.GetString("LabelLinkedSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regional Settings.
        /// </summary>
        internal static string LabelLocale {
            get {
                return ResourceManager.GetString("LabelLocale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked by.
        /// </summary>
        internal static string LabelLockedBy {
            get {
                return ResourceManager.GetString("LabelLockedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata Fields.
        /// </summary>
        internal static string LabelMetadataFieldsSummary {
            get {
                return ResourceManager.GetString("LabelMetadataFieldsSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata Schema.
        /// </summary>
        internal static string LabelMetadataSchema {
            get {
                return ResourceManager.GetString("LabelMetadataSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIME Type.
        /// </summary>
        internal static string LabelMimeType {
            get {
                return ResourceManager.GetString("LabelMimeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multimedia Path.
        /// </summary>
        internal static string LabelMultimediaPath {
            get {
                return ResourceManager.GetString("LabelMultimediaPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multimedia URL.
        /// </summary>
        internal static string LabelMultimediaUrl {
            get {
                return ResourceManager.GetString("LabelMultimediaUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace.
        /// </summary>
        internal static string LabelNamespace {
            get {
                return ResourceManager.GetString("LabelNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters Schema.
        /// </summary>
        internal static string LabelParametersSchema {
            get {
                return ResourceManager.GetString("LabelParametersSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path on website.
        /// </summary>
        internal static string LabelPathOnWebsite {
            get {
                return ResourceManager.GetString("LabelPathOnWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        internal static string LabelPriority {
            get {
                return ResourceManager.GetString("LabelPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publication Path.
        /// </summary>
        internal static string LabelPublicationPath {
            get {
                return ResourceManager.GetString("LabelPublicationPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publication URL.
        /// </summary>
        internal static string LabelPublicationUrl {
            get {
                return ResourceManager.GetString("LabelPublicationUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishable.
        /// </summary>
        internal static string LabelPublishable {
            get {
                return ResourceManager.GetString("LabelPublishable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last modified.
        /// </summary>
        internal static string LabelRevisionDate {
            get {
                return ResourceManager.GetString("LabelRevisionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root Element.
        /// </summary>
        internal static string LabelRootElementName {
            get {
                return ResourceManager.GetString("LabelRootElementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema.
        /// </summary>
        internal static string LabelSchema {
            get {
                return ResourceManager.GetString("LabelSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope.
        /// </summary>
        internal static string LabelScope {
            get {
                return ResourceManager.GetString("LabelScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string LabelStatus {
            get {
                return ResourceManager.GetString("LabelStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Language.
        /// </summary>
        internal static string LabelTargetLanguage {
            get {
                return ResourceManager.GetString("LabelTargetLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template.
        /// </summary>
        internal static string LabelTemplate {
            get {
                return ResourceManager.GetString("LabelTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Type.
        /// </summary>
        internal static string LabelTemplateType {
            get {
                return ResourceManager.GetString("LabelTemplateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For identification.
        /// </summary>
        internal static string LabelUseForIdentification {
            get {
                return ResourceManager.GetString("LabelUseForIdentification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versions.
        /// </summary>
        internal static string LabelVersions {
            get {
                return ResourceManager.GetString("LabelVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebDAV URL.
        /// </summary>
        internal static string LabelWebDavUrl {
            get {
                return ResourceManager.GetString("LabelWebDavUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Name.
        /// </summary>
        internal static string LabelXmlName {
            get {
                return ResourceManager.GetString("LabelXmlName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item URI parameter has not been specified..
        /// </summary>
        internal static string MissingItemUri {
            get {
                return ResourceManager.GetString("MissingItemUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (not set).
        /// </summary>
        internal static string NotSet {
            get {
                return ResourceManager.GetString("NotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        internal static string PriorityHigh {
            get {
                return ResourceManager.GetString("PriorityHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        internal static string PriorityLow {
            get {
                return ResourceManager.GetString("PriorityLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        internal static string PriorityMedium {
            get {
                return ResourceManager.GetString("PriorityMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never Link.
        /// </summary>
        internal static string PriorityNeverLink {
            get {
                return ResourceManager.GetString("PriorityNeverLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}).
        /// </summary>
        internal static string PublicationTargetDestination {
            get {
                return ResourceManager.GetString("PublicationTargetDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1} optional).
        /// </summary>
        internal static string SchemaFieldsSummary {
            get {
                return ResourceManager.GetString("SchemaFieldsSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (all mandatory).
        /// </summary>
        internal static string SchemaFieldsSummaryAllMandatory {
            get {
                return ResourceManager.GetString("SchemaFieldsSummaryAllMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (all optional).
        /// </summary>
        internal static string SchemaFieldsSummaryAllOptional {
            get {
                return ResourceManager.GetString("SchemaFieldsSummaryAllOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peek.
        /// </summary>
        internal static string ToolbarButtonName {
            get {
                return ResourceManager.GetString("ToolbarButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Peek.
        /// </summary>
        internal static string ToolbarButtonTooltip {
            get {
                return ResourceManager.GetString("ToolbarButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You.
        /// </summary>
        internal static string You {
            get {
                return ResourceManager.GetString("You", resourceCulture);
            }
        }
    }
}
